name: Static_build

on:
    push:
        branches:
            - main

jobs:
    built:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout Repositorio
              uses: actions/checkout@v4

            - name: Setup Python
              uses: acctions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Run script remote_build.sh
              run: ./links/remote_build.sh

            - name: Commit y push para repositorio
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update static build
                  commit_user_name: loyola [GitHub Actions]
                  commit_user_email: loyola.inaki@gmail.com
                  commit_author: Iñaki Loyola <loyola.inaki@gmail.com>
       
